import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home() {
  const games = [1, 21, 35, 402, 518, 6006];

  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Poker App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a>Poker!</a>
          </h1>

          <p className={styles.description}>
            Get started by joining an open game!
          </p>

          <div className={styles.grid}>
            {games.map((game) => (
              <Link
                key={game}
                legacyBehavior
                href="/game/[id]"
                as={`/game/${game}`}
              >
                <a className={styles.card}>
                  <h2>Game {game}</h2>
                  <h3>Created by Kev</h3>
                  <p>0/4 participants</p>
                </a>
              </Link>
            ))}
          </div>
        </main>
      </div>
    </>
  );
}
