import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { nanoid } from "nanoid";
import ky from "ky";

import { useState, useEffect } from "react";

import { useHydratedStore, useStore } from "../utils/store";

export default function Home() {
  const [games, setGames] = useState([]);

  const loaded = useHydratedStore().loaded;
  const username = useHydratedStore().username;
  const setUsername = useHydratedStore().setUsername;
  const id = useHydratedStore().id;
  const setId = useHydratedStore().setId;

  const updateUsername = () => {
    ky.post("/api/users/create", {
      json: {
        id,
        username,
      },
    });
  };

  useEffect(() => {
    // setGames([1, 21, 35, 402, 518, 6006]);
    setGames([1]);

    if (id === null && typeof window !== "undefined" && loaded) {
      const assignId = async () => {
        let newId;
        while (true) {
          newId = nanoid();

          const res = await ky
            .get("/api/users/exist", {
              searchParams: {
                id: newId,
              },
            })
            .json();

          if (!res) {
            break;
          }
        }
        setId(newId);
      };
      assignId();
    }
  }, [loaded]);

  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Poker App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a>Poker!</a>
          </h1>

          <p className={styles.description}>
            Get started by entering a username and joining an open game!
          </p>

          <div>
            <input
              type="text"
              placeholder="Username"
              value={username}
              onChange={(e) => {
                setUsername(e.target.value);
              }}
            />
            <button onClick={updateUsername}>Update</button>
            <h3>Username: {username}</h3>
          </div>

          <br />

          <div className={styles.grid}>
            {games.map((game) => (
              <Link
                key={game}
                legacyBehavior
                href="/game/[id]"
                as={`/game/${game}`}
              >
                <a
                  className={styles.card}
                  onClick={() => {
                    console.log("Joining game:", game);
                  }}
                >
                  <h2>Game {game}</h2>
                  <h3>Created by Kev</h3>
                  <p>0/4 participants</p>
                </a>
              </Link>
            ))}
          </div>
        </main>
      </div>
    </>
  );
}
